openapi: 3.1.0
info:
  title: Ticketing System API
  version: 1.0.0
  description: API for managing users in the ticketing system.
servers:
  - url: http://localhost:3000/api
security:
  - bearerAuth: []
paths:
  /users:
    get:
      summary: Get all users
      description: Returns a list of all users (ADMIN only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /users/me:
    get:
      summary: Get current logged-in user
      description: Returns information about the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      summary: Update current user
      description: Update authenticated user's information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Updated user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
    delete:
      summary: Delete current user
      description: Deletes the authenticated user
      security:
        - bearerAuth: []
      responses:
        '204':
          description: User deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/{id}/role:
    patch:
      summary: Update a user's role
      description: Change the role of a user (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRoleUpdate'
      responses:
        '200':
          description: User role updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john@example.com
        birthday:
          type: string
          format: date
          example: '1990-01-01'
        role:
          type: string
          enum:
            - CUSTOMER
            - ADMIN
            - ORGANIZER
          example: CUSTOMER
    UserUpdate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        birthday:
          type: string
          format: date
        password:
          type: string
          format: password
    UserRoleUpdate:
      type: object
      properties:
        role:
          type: string
          enum:
            - CUSTOMER
            - ADMIN
            - ORGANIZER
  responses:
    Unauthorized:
      description: Unauthorized access (missing or invalid token)
    Forbidden:
      description: Forbidden (insufficient permissions)
    BadRequest:
      description: Validation error / bad request
