openapi: 3.1.0
info:
  title: Ticketing System API
  version: 1.0.0
  description: API for managing users in the ticketing system.
servers:
  - url: http://localhost:3000/api
security:
  - bearerAuth: []
tags:
  - name: Authentication
    description: Sign-up and login users
  - name: Users
    description: User information
  - name: Events
    description: Information about events
  - name: Tickets
    description: Tickets associated with events
  - name: Orders
    description: Tickets purchased by customers
paths:
  /users:
    get:
      summary: Get all users
      description: Returns a list of all users (ADMIN only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /users/me:
    get:
      summary: Get current logged-in user
      description: Returns information about the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      summary: Update current user
      description: Update authenticated user's information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Updated user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
    delete:
      summary: Delete current user
      description: Deletes the authenticated user
      security:
        - bearerAuth: []
      responses:
        '204':
          description: User deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
  /users/{id}/role:
    patch:
      summary: Update a user's role
      description: Change the role of a user (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRoleUpdate'
      responses:
        '200':
          description: User role updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /orders:
    post:
      summary: Create new order
      tags:
        - Orders
      description: Creates a new order (authenticated only)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ticketIds
              properties:
                ticketIds:
                  type: array
                  items:
                    type: integer
                  example:
                    - 1
                    - 2
                    - 3
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
  /orders/me:
    get:
      summary: Get all orders
      tags:
        - Orders
      description: Returns all orders by the authenticated person
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
  /order/me/{id}:
    get:
      summary: Get order
      tags:
        - Orders
      description: Returns the specific order by the authenticated person
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Respective order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /order/{id}/status:
    patch:
      summary: Cancel an order
      tags:
        - Orders
      description: Cancels the order and makes tickets available again
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
  /orders/{id}:
    delete:
      summary: Delete order
      tags:
        - Orders
      description: Delete an order by its ID (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '204':
          description: Order deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: john@example.com
        birthday:
          type: string
          format: date
          example: '1990-01-01'
        role:
          type: string
          enum:
            - CUSTOMER
            - ADMIN
            - ORGANIZER
          example: CUSTOMER
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          example: You are not authenticated
    ForbiddenError:
      type: object
      properties:
        error:
          type: string
          example: You have insufficient permissions
    UserUpdate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        birthday:
          type: string
          format: date
        password:
          type: string
          format: password
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
    UserRoleUpdate:
      type: object
      properties:
        role:
          type: string
          enum:
            - CUSTOMER
            - ADMIN
            - ORGANIZER
    Order:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userId:
          type: integer
          example: 2
        total:
          type: number
          format: float
          example: 99.99
        orderStatus:
          type: string
          enum:
            - COMPLETED
            - CANCELLED
          example: COMPLETED
        orderTickets:
          type: array
          items:
            type: object
            properties:
              ticketId:
                type: integer
                example: 10
              quantity:
                type: integer
                example: 2
        createdAt:
          type: string
          format: date-time
          example: '2025-02-15T10:30:00Z'
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: Id not found
    ConflictError:
      type: object
      properties:
        error:
          type: string
          example: Already exists
  responses:
    Unauthorized:
      description: Unauthorized access (missing or invalid token)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
    Forbidden:
      description: Forbidden (insufficient permissions)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
    Conflict:
      description: Conflicting requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConflictError'
